# Data wrangling

TODO: intro

### Table of contents

- Numpy arrays
 - creation
   - randomness
 - accessing
 - operations
 - broadcasting



- Pandas dataframes
 - creation
 - accessing
 - extension
 - missing values
 - deletion
 - operations
 - aggregation
 - loading and saving


- Further reading

TODO: links

TODO: exercises

## Arrays

- **Numpy**: numeric computation
 - array operations
 - masking
 - smoothening filter

won't touch any linear algebra topics (matrix multiplication, etc)

In [2]:
import numpy as np

usually homogenous

must have all dimensions equal, can't have 
```
[
 [1,2,3], 
 [1,2]
]
```

In [3]:
squares = np.array([0, 1, 4, 9, 16, 25, 36])

## accessing

like lists

In [4]:
indices = [5, 2, 1]
squares[indices]  # can also access using multiple indices

array([25,  4,  1])

In [5]:
squares + 100

array([100, 101, 104, 109, 116, 125, 136])

In [6]:
np.arange(10) ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

---

In [7]:
mask = (squares > 5)

In [8]:
mask

array([False, False, False,  True,  True,  True,  True])

In [9]:
squares[mask]

array([ 9, 16, 25, 36])

---

In [10]:
# arrays can be n-dimensional
m = np.array([
    [5, 2, 3],
    [4, 5, 1],
    [7, 1, 2],
    [6, 2, 9]
])

In [11]:
m.shape

(4, 3)

In [12]:
m * 10

array([[50, 20, 30],
       [40, 50, 10],
       [70, 10, 20],
       [60, 20, 90]])

In [13]:
m[:2]  # first two rows

array([[5, 2, 3],
       [4, 5, 1]])

In [14]:
m[:, :2]  # all rows, first two columns

array([[5, 2],
       [4, 5],
       [7, 1],
       [6, 2]])

In [15]:
m[:2, :2]  # first two rows of the first two columns

array([[5, 2],
       [4, 5]])

---

reshaping

In [16]:
a = np.arange(12)

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
a.reshape(4, 3)  # 4 rows, 3 columns

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

---

more than two dimensions

In [19]:
R = [1, 0, 0]  # red
B = [0, 0, 1]  # blue
W = [1, 1, 1]  # white

In [20]:
picture = np.array([
    [B, B, R, R],
    [B, B, W, W],
    [R, R, R, R],
    [W, W, W, W],
    [R, R, R, R],
    [W, W, W, W],
])

In [21]:
picture

array([[[0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 0]],

       [[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [22]:
picture.shape  # rank is the number of dimensions, three in this case

(6, 4, 3)

most functions allow you to specify an axis

In [23]:
picture.sum()  # overall

44

TODO: exemplify axis in 2D

In [24]:
picture.sum(axis=0)  # sum of each column

array([[4, 2, 4],
       [4, 2, 4],
       [6, 3, 3],
       [6, 3, 3]])

In [25]:
picture.sum(axis=1)  # sum of each row

array([[2, 0, 2],
       [2, 2, 4],
       [4, 0, 0],
       [4, 4, 4],
       [4, 0, 0],
       [4, 4, 4]])

In [26]:
picture.sum(axis=2)  # the sum of all three color channels

array([[1, 1, 1, 1],
       [1, 1, 3, 3],
       [1, 1, 1, 1],
       [3, 3, 3, 3],
       [1, 1, 1, 1],
       [3, 3, 3, 3]])

---

### Broadcasting

In [27]:
picture

array([[[0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 0]],

       [[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [28]:
picture + 10  # add 10 to each element

array([[[10, 10, 11],
        [10, 10, 11],
        [11, 10, 10],
        [11, 10, 10]],

       [[10, 10, 11],
        [10, 10, 11],
        [11, 11, 11],
        [11, 11, 11]],

       [[11, 10, 10],
        [11, 10, 10],
        [11, 10, 10],
        [11, 10, 10]],

       [[11, 11, 11],
        [11, 11, 11],
        [11, 11, 11],
        [11, 11, 11]],

       [[11, 10, 10],
        [11, 10, 10],
        [11, 10, 10],
        [11, 10, 10]],

       [[11, 11, 11],
        [11, 11, 11],
        [11, 11, 11],
        [11, 11, 11]]])

In [29]:
picture + [10, 0, 0]  # add 10 to the Red channel of every pixel

array([[[10,  0,  1],
        [10,  0,  1],
        [11,  0,  0],
        [11,  0,  0]],

       [[10,  0,  1],
        [10,  0,  1],
        [11,  1,  1],
        [11,  1,  1]],

       [[11,  0,  0],
        [11,  0,  0],
        [11,  0,  0],
        [11,  0,  0]],

       [[11,  1,  1],
        [11,  1,  1],
        [11,  1,  1],
        [11,  1,  1]],

       [[11,  0,  0],
        [11,  0,  0],
        [11,  0,  0],
        [11,  0,  0]],

       [[11,  1,  1],
        [11,  1,  1],
        [11,  1,  1],
        [11,  1,  1]]])

In [30]:
picture + [
    [10, 0,  0],
    [10, 0,  0],
    [0,  0, 10],
    [0,  0, 10],
]  # add this to each horizontal line of pixels in the picture

array([[[10,  0,  1],
        [10,  0,  1],
        [ 1,  0, 10],
        [ 1,  0, 10]],

       [[10,  0,  1],
        [10,  0,  1],
        [ 1,  1, 11],
        [ 1,  1, 11]],

       [[11,  0,  0],
        [11,  0,  0],
        [ 1,  0, 10],
        [ 1,  0, 10]],

       [[11,  1,  1],
        [11,  1,  1],
        [ 1,  1, 11],
        [ 1,  1, 11]],

       [[11,  0,  0],
        [11,  0,  0],
        [ 1,  0, 10],
        [ 1,  0, 10]],

       [[11,  1,  1],
        [11,  1,  1],
        [ 1,  1, 11],
        [ 1,  1, 11]]])

TODO: dtype

---

## creating

In [31]:
np.ones(4)

array([1., 1., 1., 1.])

In [32]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.zeros_like(squares)

array([0, 0, 0, 0, 0, 0, 0])

In [34]:
# conversion
squares.astype(float)

array([ 0.,  1.,  4.,  9., 16., 25., 36.])

TODO: asarray, copy and deepcopy explanations

In [35]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
np.arange(10)  # same as built-in range, but result comes out as a numpy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.linspace(start=0, stop=15, num=11)  # like "range" but allows for non-integer increments

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ])

TODO: np.sin

## Randomness

In [38]:
np.random.seed(123)  # allows reproducibility of results

In [39]:
np.random.rand(4, 2)  # uniformly distributed [0, 1]

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [40]:
np.random.randn(3)  # standard normal distribution ~N(0, 1)

array([-2.42667924, -0.42891263,  1.26593626])

In [41]:
np.random.randint(0, 10, size=3)

array([3, 4, 0])

In [42]:
np.random.choice(['red', 'green', 'blue'], size=5)

array(['red', 'red', 'green', 'blue', 'red'], dtype='<U5')

In [43]:
np.random.permutation([4, 2, 1])

array([2, 4, 1])

## operations

a+b

~a
-a

a.sum()
a.std()
a.max

a.argmin

m.T

## Dataframes

- **Pandas**: powerful dataframes
 - pivoting
 - grouping

In [44]:
import pandas as pd

In [45]:
# like matrix, but made for labeled data, and with functionality built in

In [46]:
students = pd.DataFrame({
    'height':    np.random.randint(150, 200, size=5),
    'weight':    np.random.randint(50,  100, size=5),
    'graduated': np.random.random(size=5) > .5,  # same as np.random.randint(0, 1, size=10).astype(bool)
})

In [47]:
students

height  weight  graduated
0     197      78      False
1     198      88      False
2     157      83       True
3     191      71      False
4     185      80      False

In [48]:
students.index = list('abcde')  # it is implicitly indexed by numbers, but we can change that

In [49]:
students

height  weight  graduated
a     197      78      False
b     198      88      False
c     157      83       True
d     191      71      False
e     185      80      False

In [50]:
len(students)

5

In [51]:
students.dtypes

height       int64
weight       int64
graduated     bool
dtype: object

In [52]:
students.height.astype(float)

a    197.0
b    198.0
c    157.0
d    191.0
e    185.0
Name: height, dtype: float64

### Accessing

In [53]:
students.loc['a']  # we can now acess either by their name

height         197
weight          78
graduated    False
Name: a, dtype: object

In [54]:
students.iloc[0]  # or by their position

height         197
weight          78
graduated    False
Name: a, dtype: object

In [55]:
students[:3]

height  weight  graduated
a     197      78      False
b     198      88      False
c     157      83       True

In [56]:
students.graduated  # we can also access column-wise

a    False
b    False
c     True
d    False
e    False
Name: graduated, dtype: bool

In [57]:
columns = ['weight', 'height']
students[columns]

weight  height
a      78     197
b      88     198
c      83     157
d      71     191
e      80     185

In [58]:
students[students.graduated]  # use the boolean column as a mask

height  weight  graduated
c     157      83       True

In [59]:
for column in students:
    print(column)

height
weight
graduated


In [60]:
for student, rows in students.iterrows():
    print(student, rows.height)

a 197
b 198
c 157
d 191
e 185


### Adding

In [61]:
students.loc['x'] = (170, 70, True)  # adding a new row

In [62]:
students

height  weight  graduated
a     197      78      False
b     198      88      False
c     157      83       True
d     191      71      False
e     185      80      False
x     170      70       True

In [63]:
students['age'] = np.random.randint(18, 24, size=6)  # adding a new column

In [64]:
students

height  weight  graduated  age
a     197      78      False   20
b     198      88      False   20
c     157      83       True   20
d     191      71      False   23
e     185      80      False   20
x     170      70       True   22

In [65]:
# create a column based on another
students['can_ride'] = (students.height > 170)  # "you must be this tall to ride the roller coaster"

In [66]:
students

height  weight  graduated  age  can_ride
a     197      78      False   20      True
b     198      88      False   20      True
c     157      83       True   20     False
d     191      71      False   23      True
e     185      80      False   20      True
x     170      70       True   22     False

---

In [67]:
new_students = pd.DataFrame({
    'height': [160, 180],
    'weight': [ 60,  80],
})

In [68]:
new_students

height  weight
0     160      60
1     180      80

In [69]:
students = pd.concat([students, new_students], sort=False)
students

height  weight graduated   age can_ride
a     197      78     False  20.0     True
b     198      88     False  20.0     True
c     157      83      True  20.0    False
d     191      71     False  23.0     True
e     185      80     False  20.0     True
x     170      70      True  22.0    False
0     160      60       NaN   NaN      NaN
1     180      80       NaN   NaN      NaN

In [70]:
n_students = len(students)
new_info = pd.DataFrame({
    'fav_number':   np.random.randint(0, 100, size=n_students),
    'fav_icecream': np.random.choice(['vanilla', 'chocolate', 'strawberry'], size=n_students),
})
new_info.index = students.index

In [71]:
new_info

fav_number fav_icecream
a          15   strawberry
b          27      vanilla
c          30   strawberry
d          52    chocolate
e          70   strawberry
x          26    chocolate
0          80    chocolate
1           6   strawberry

In [72]:
students = students.merge(new_info, left_index=True, right_index=True)
students

height  weight graduated   age can_ride  fav_number fav_icecream
a     197      78     False  20.0     True          15   strawberry
b     198      88     False  20.0     True          27      vanilla
c     157      83      True  20.0    False          30   strawberry
d     191      71     False  23.0     True          52    chocolate
e     185      80     False  20.0     True          70   strawberry
x     170      70      True  22.0    False          26    chocolate
0     160      60       NaN   NaN      NaN          80    chocolate
1     180      80       NaN   NaN      NaN           6   strawberry

---

### missing values

In [73]:
students.style.highlight_null()

In [74]:
pd.isna(students)

height  weight  graduated    age  can_ride  fav_number  fav_icecream
a   False   False      False  False     False       False         False
b   False   False      False  False     False       False         False
c   False   False      False  False     False       False         False
d   False   False      False  False     False       False         False
e   False   False      False  False     False       False         False
x   False   False      False  False     False       False         False
0   False   False       True   True      True       False         False
1   False   False       True   True      True       False         False

In [75]:
pd.isna(students.age)

a    False
b    False
c    False
d    False
e    False
x    False
0     True
1     True
Name: age, dtype: bool

In [76]:
students.dropna()

height  weight graduated   age can_ride  fav_number fav_icecream
a     197      78     False  20.0     True          15   strawberry
b     198      88     False  20.0     True          27      vanilla
c     157      83      True  20.0    False          30   strawberry
d     191      71     False  23.0     True          52    chocolate
e     185      80     False  20.0     True          70   strawberry
x     170      70      True  22.0    False          26    chocolate

In [77]:
students.fillna({
    'graduated': False,
    'can_ride':  False,
    'age':       20,
})

height  weight  graduated   age  can_ride  fav_number fav_icecream
a     197      78      False  20.0      True          15   strawberry
b     198      88      False  20.0      True          27      vanilla
c     157      83       True  20.0     False          30   strawberry
d     191      71      False  23.0      True          52    chocolate
e     185      80      False  20.0      True          70   strawberry
x     170      70       True  22.0     False          26    chocolate
0     160      60      False  20.0     False          80    chocolate
1     180      80      False  20.0     False           6   strawberry

---

### Deleting

TODO: mutability and inplace

In [78]:
students.drop('height', axis=1)  # delete entire columns

weight graduated   age can_ride  fav_number fav_icecream
a      78     False  20.0     True          15   strawberry
b      88     False  20.0     True          27      vanilla
c      83      True  20.0    False          30   strawberry
d      71     False  23.0     True          52    chocolate
e      80     False  20.0     True          70   strawberry
x      70      True  22.0    False          26    chocolate
0      60       NaN   NaN      NaN          80    chocolate
1      80       NaN   NaN      NaN           6   strawberry

In [79]:
students.dropna(inplace=True)

In [80]:
mask = (students.age > 21)  # delete some rows
students[mask]

height  weight graduated   age can_ride  fav_number fav_icecream
d     191      71     False  23.0     True          52    chocolate
x     170      70      True  22.0    False          26    chocolate

### Array operations

Array-wise functions are naturally extended to Series

In [87]:
students  # to see what we're working with

height  weight graduated   age can_ride  fav_number fav_icecream
a     197      78     False  20.0     True          15   strawberry
b     198      88     False  20.0     True          27      vanilla
c     157      83      True  20.0    False          30   strawberry
d     191      71     False  23.0     True          52    chocolate
e     185      80     False  20.0     True          70   strawberry
x     170      70      True  22.0    False          26    chocolate

In [82]:
students.mean()

height        183.000000
weight         78.333333
graduated       0.333333
age            20.833333
can_ride        0.666667
fav_number     36.666667
dtype: float64

**ℹ️ Tip**: The sum of the boolean series `graduated` is the number of people that graduated. The mean of `graduated` is the sum divided by the total number of students, which is precisely the percentage of students that graduated.

In [83]:
students.graduated.sum()

2

In [84]:
students.mean(axis=1)  # the average for each student, of their height, weight and graduation status.. which doesn't make much sense

a    77.50
b    83.25
c    72.50
d    84.25
e    88.75
x    72.00
dtype: float64

In [85]:
students.weight - 10  # if only losing weight was this easy 😅

a    68
b    78
c    73
d    61
e    70
x    60
Name: weight, dtype: int64

In [86]:
students.height + students.weight

a    275
b    286
c    240
d    262
e    265
x    240
dtype: int64

In [89]:
students.graduated & ~students.can_ride  # students who graduated but cannot ride

a    False
b    False
c     True
d    False
e    False
x     True
dtype: bool

In [90]:
students.weight.apply(lambda w: (w // 10) * 10)  # apply to each element of a column

a    70
b    80
c    80
d    70
e    80
x    70
Name: weight, dtype: int64

In [91]:
students.apply(lambda row: row.height + row.weight, axis=1)  # apply row-wise

a    275
b    286
c    240
d    262
e    265
x    240
dtype: int64

In [92]:
def relabel_boolean(x):
    # if the argument is not a boolean, leave it as it is
    if type(x) is not bool:
        return x
    # True -> yes; False -> no
    return 'yes' if x is True else 'no'

In [93]:
students.applymap(relabel_boolean)  # apply element-wise

height  weight graduated   age can_ride  fav_number fav_icecream
a     197      78        no  20.0      yes          15   strawberry
b     198      88        no  20.0      yes          27      vanilla
c     157      83       yes  20.0       no          30   strawberry
d     191      71        no  23.0      yes          52    chocolate
e     185      80        no  20.0      yes          70   strawberry
x     170      70       yes  22.0       no          26    chocolate

**ℹ️ Tip**: writing guards for early-exit before processing takes place reduces indentation levels and makes the code readable:
```python
if check_1:
    # some pre-processing
    if check_2:
        # some processing
        return all_good
    else:
        return failed_check_2
else:
    return failed_check_1
```

Equivalent implementation with fewer levels of indentation:
```python
if not check_1:
    return failed_check_1
# some pre-processing
if not check_2:
    return failed_check_2
# some processing
return all_good
```

### Data manipulation

want to know the avg height and weight for those students that graduated and those that did not

In [111]:
# pivoting "flips" the data according to a discrete variable
pd.pivot_table(
    students,
    index='graduated',
    values=['height', 'weight'],
    aggfunc='mean',
)

height  weight
graduated                
False      192.75   79.25
True       163.50   76.50

In [112]:
pd.pivot_table(
    students,
    index='graduated',
    values=['height', 'weight'],
    aggfunc='max',
)

height  weight
graduated                
False         198      88
True          170      83

---

Melting can be thought of as the reverse of pivoting

In [113]:
height_evolution = pd.DataFrame({
    'alice': np.linspace(160, 190, num=5),
    'bob':   np.linspace(170, 180, num=5),
    'year':  range(2000, 2005),
})

In [114]:
height_evolution

alice    bob  year
0  160.0  170.0  2000
1  167.5  172.5  2001
2  175.0  175.0  2002
3  182.5  177.5  2003
4  190.0  180.0  2004

In [115]:
melted = height_evolution.melt(
    id_vars='year',
    value_vars=['alice', 'bob'],

    var_name='student',
    value_name='height',
)
melted

year student  height
0  2000   alice   160.0
1  2001   alice   167.5
2  2002   alice   175.0
3  2003   alice   182.5
4  2004   alice   190.0
5  2000     bob   170.0
6  2001     bob   172.5
7  2002     bob   175.0
8  2003     bob   177.5
9  2004     bob   180.0

In [116]:
melted.student.str.title()  # apply string functions on the entire column

0    Alice
1    Alice
2    Alice
3    Alice
4    Alice
5      Bob
6      Bob
7      Bob
8      Bob
9      Bob
Name: student, dtype: object

---

In [117]:
students

height  weight graduated   age can_ride  fav_number fav_icecream
a     197      78     False  20.0     True          15   strawberry
b     198      88     False  20.0     True          27      vanilla
c     157      83      True  20.0    False          30   strawberry
d     191      71     False  23.0     True          52    chocolate
e     185      80     False  20.0     True          70   strawberry
x     170      70      True  22.0    False          26    chocolate

In [118]:
# you can also create dataframes row-wise
performance = pd.DataFrame([
    ('alice', 'CS101', 4.0),
    ('alice', 'CS102', 3.0),
    ('alice', 'CS201', 4.0),
    ('bob',   'CS101', 3.0),
    ('bob',   'CS201', 4.0),
], columns=['student', 'class', 'grade'])

In [119]:
performance

student  class  grade
0   alice  CS101    4.0
1   alice  CS102    3.0
2   alice  CS201    4.0
3     bob  CS101    3.0
4     bob  CS201    4.0

In [120]:
performance.groupby('student').grade.mean()

student
alice    3.666667
bob      3.500000
Name: grade, dtype: float64

In [121]:
# group by multiple variables
students.groupby(['graduated', 'fav_icecream']).age.mean()

graduated  fav_icecream
False      chocolate       23.0
           strawberry      20.0
           vanilla         20.0
True       chocolate       22.0
           strawberry      20.0
Name: age, dtype: float64

In [122]:
for student, rows in performance.groupby('student'):
    print(student, 'took', len(rows), 'classes, with an average of', rows.grade.mean())

alice took 3 classes, with an average of 3.6666666666666665
bob took 2 classes, with an average of 3.5


---

In [123]:
max_height = height_evolution.max()
max_height

alice     190.0
bob       180.0
year     2004.0
dtype: float64

In [124]:
max_height.name = 'latest_height'

In [125]:
performance.join(max_height, on='student')
# note that "year" is not here

student  class  grade  latest_height
0   alice  CS101    4.0          190.0
1   alice  CS102    3.0          190.0
2   alice  CS201    4.0          190.0
3     bob  CS101    3.0          180.0
4     bob  CS201    4.0          180.0

---

### Loading

In [126]:
pd.read_json('example_files/objects.json')

grade   name  year
0   3.90  Alice     2
1   3.80    Bob     3
2   3.85  Chris     1

In [127]:
pd.read_csv('example_files/tabular.csv')

grade   name  year
0   3.90  Alice     2
1   3.80    Bob     3
2   3.85  Chris     1

In [128]:
# load directly from an url, letting Pandas do the downloading
pd.read_csv('https://raw.githubusercontent.com/stefan-niculae/viz-workshop/master/example_files/tabular.csv')

grade   name  year
0   3.90  Alice     2
1   3.80    Bob     3
2   3.85  Chris     1

In [129]:
# load directly from an archive, letting Pandas do the uncompressing
pd.read_csv('example_files/archived.csv.zip')

grade   name  year
0   3.90  Alice     2
1   3.80    Bob     3
2   3.85  Chris     1

In [130]:
performance.to_csv('students_performance.csv')  # you can check the result in the file browser

## Read more
 - Numpy: [quickstart guide](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html)
 - Scipy: [tutorial](https://docs.scipy.org/doc/scipy/reference/tutorial/index.html)
 - Python/Numpy/Scipy/Matplotlib: [quick tutorial](http://cs231n.github.io/python-numpy-tutorial/)