# Data Wrangling

Crash course into data generation, handling, manipulation, transformatio and preparation. This can lead to further analysis: statistical or visual (which we will explore in workshop 3) or training of predictive models. This assumes the data is already cleaned and structured, not in raw form (which we will briefly explore in workshop 4).

Pre-requisites: basic understanding of programming, Python is a plus.

### Table of contents

- Numpy Arrays
   - Creation
   - Properties
     - Shape
     - Data Type
  - Generation
    - Randomness
  - Accessing
    - Iteration
  - Copying
  - Array Operations
    - Arithmetic
    - Logical
    - Reshaping
    - Broadcasting
    - Masking
   - Extension

  

- Pandas Dataframes
   - Creation
   - Properties
   - Accessing
   - Extension
   - Missing values
   - Deletion
   - Operations
      - Arithmetic
      - Logical
      - String Functions
      - Arbitrary Functions
      - Statistical
      - Ordering
   - Data Transformations
      - Group By
      - Pivot
      - Melt
      - Join
   - Time Series
   - Hierarchical Indices
   - Loading and Saving Dataframes



- Further Reading

## Numpy Arrays

Numpy offers powerful array objects. It is part of the de-facto [Python ecosystem](https://www.scipy.org) for mathematics, science and engineering, and sits at the foundation of most scientific computation libraries.

They are homogenous (all elements are the same type) containers, usually for numbers, that indexed by integers. They are similar to lists but offer much more functionality and performance.

In [1]:
import numpy as np  # import the package into our namespace, under the usual name `np`

### Array Creation

Create an array from a regular `list`s object:

In [2]:
squares = np.array([0, 1, 4, 9, 16, 25, 36, 49])

In [3]:
squares

array([ 0,  1,  4,  9, 16, 25, 36, 49])

Create a 2D array/a matrix:

In [4]:
m = np.array([
    [5, 2, 3],
    [4, 5, 1],
    [7, 1, 2],
    [6, 2, 9],
])

In [5]:
m

array([[5, 2, 3],
       [4, 5, 1],
       [7, 1, 2],
       [6, 2, 9]])

Arbitrarily many dimensions dimensions:

In [6]:
# pixels, which are 3-dimensional points:
R = [1, 0, 0]  # red
B = [0, 0, 1]  # blue
W = [1, 1, 1]  # white

In [8]:
image = np.array([
    [B, B, R, R],
    [B, B, W, W],
    [R, R, R, R],
    [W, W, W, W],
    [R, R, R, R],
    [W, W, W, W],
])

In [9]:
image

array([[[0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 0]],

       [[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

**💪 Exercise**: create a numpy array of three rows, two columns of arbitrary numbers from `0` to `5`:

In [10]:
np.array([
    [2, 1],
    [4, 2],
    [2, 1],
])

array([[2, 1],
       [4, 2],
       [2, 1]])

#### Array Shape

The _shape_ of each array is the size of each dimension:

In [13]:
squares

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [11]:
squares.shape  # 8 elements

(8,)

In [12]:
m.shape  # 4 rows, 3 columns

(4, 3)

In [14]:
image.shape  # 6 rows, 4 columns, each element containing 3 coordinates

(6, 4, 3)

An array's _rank_ is the number of dimensions.

---

All dimensions must have equal size, meaning we can't have something like:

In [15]:
a = np.array([
    [1,2,3], 
    [1,2]
])
a

array([list([1, 2, 3]), list([1, 2])], dtype=object)

In [16]:
a.shape

(2,)

It just interpreted it as an array of two elements, each element being a list. More details in the next sub-section.

#### Array Data Types

An array's data type is the type of the object they are holding.

In [17]:
squares.dtype

dtype('int64')

In [18]:
m.dtype

dtype('int64')

In [19]:
np.array([1.5, 2.3, 4.9]).dtype

dtype('float64')

In [20]:
np.array([True, True, False]).dtype

dtype('bool')

In [22]:
np.array(['abcfdafdsf', 'def', 'xy']).dtype  # unicode with 3 or fewer characters

dtype('<U10')

Compatible datatypes are "up-scaled":

In [23]:
a = np.array([True, 5])
a

array([1, 5])

In [24]:
a.dtype

dtype('int64')

In [25]:
np.array([1, 2.5]).dtype

dtype('float64')

In [26]:
np.array([True, 2, 3.5]).dtype

dtype('float64')

In [27]:
np.array([7, 'abc']).dtype  # calls `str` on them

dtype('<U21')

Incompatible datatypes are put under the `object` umbrella:

In [28]:
s = {1, 2, 3}
np.array([s, 5]).dtype

dtype('O')

You can also call type conversion manually:

In [29]:
np.array([2, 4, 0]).astype(bool)

array([ True,  True, False])

In [30]:
np.array([2, 4, 0]).astype(float)

array([2., 4., 0.])

Or upon creation:

In [31]:
np.array([2, 4], dtype=float)

array([2., 4.])

In [34]:
np.array([
    [1, 2, 3]
]).shape

(1, 3)

In [35]:
np.array([
    [1], 
    [2], 
    [3]
]).shape

(3, 1)

In [37]:
np.array([1, 2, 3]).shape

(3,)

**💪 Exercise**: create an array of three booleans, of `dtype` `str`:

In [38]:
np.array([True, True, False], dtype=str)

array(['True', 'True', 'False'], dtype='<U5')

#### Array Generation

Similar to the built-in `range`, generate an array of sequential numbers:

In [39]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

**ℹ️ Tip**: it's called `a range` as in `an interval`, not `arrange` as in `align` — it confused me for the longest time.

A more powerful, non-integer counterpart:

In [40]:
np.linspace(start=0, stop=15, num=5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

Similarly, there is a logarithmic counterpart:

In [41]:
np.logspace(0, 3, num=4, base=10.)

array([   1.,   10.,  100., 1000.])

---

Generate an array of equal elements:

In [42]:
np.ones(4)

array([1., 1., 1., 1.])

In [43]:
np.zeros((3, 2))  # any shape

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Specify shape based on another array's:

In [45]:
np.zeros(m.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.zeros_like(m)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
np.zeros_like(squares)  # same shape and dtype as `squares`

array([0, 0, 0, 0, 0, 0, 0, 0])

If you just want to instantiate an array, filling the elements later, you skip the filling step, and create one with bogus elements:

In [51]:
np.empty(30)  # the address where it is assigned is arbitrary, so you will likely see different results each time this is ran

array([-1.72723371e-077, -1.72723371e-077,  1.43279037e-322,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000, -1.72723371e-077,
       -1.72723371e-077,  1.08694442e-322,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000, -1.72723371e-077, -1.72723371e-077])

**💪 Exercise**: generate an array of 6 rows, 3 columns of ones:

In [52]:
np.ones((6, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Array Copying

Assign a new "label" to the same array object (similar to `&` references in C-like languages):

In [54]:
a = np.ones(3)  # create an array, and "assign the label" `a` to it
a

array([1., 1., 1.])

In [55]:
b = a  # `b` is now another label for the same array

Modifications in any label affect the base object:

In [56]:
b[0] = 5
b

array([5., 1., 1.])

In [57]:
a  # modified indirectly

array([5., 1., 1.])

---

To "clone" the object, use `copy` instead:

In [59]:
a = np.ones(3)
a

array([1., 1., 1.])

In [60]:
b = np.copy(a)

In [61]:
b[0] = 5
b

array([5., 1., 1.])

In [62]:
a

array([1., 1., 1.])

**ℹ️ Tip**: this still fails if you store non-primitive data types:

In [63]:
a = np.array([
    {1, 2, 3},  # a set
    {5, 4},
])
a

array([{1, 2, 3}, {4, 5}], dtype=object)

In [64]:
b = np.copy(a)

In [65]:
b[0].remove(3)
b

array([{1, 2}, {4, 5}], dtype=object)

In [66]:
a  # still affected

array([{1, 2}, {4, 5}], dtype=object)

In this case, `deepcopy` would be useful, from the [copy built-in library](https://docs.python.org/3.7/library/copy.html).

#### Randomness

Generating random numbers sees more use in training predictive models, but they can also be relevant in terms of example data. It also has some uses in some advanced data visualizations.

Uniformly distributed $V \sim U(0, 1)$:

In [68]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
np.random.rand(4, 2)

array([[0.70313797, 0.37571694],
       [0.41973621, 0.60306788],
       [0.57418435, 0.01405431],
       [0.41767998, 0.46477179]])

Normal standard distribution, zero-centered and unit deviation $\sim N(0, 1)$:

In [69]:
np.random.randn(3)

array([-0.30387389,  1.40181374, -0.09527534])

Uniformly distributed integers in an interval $V \sim U_{\mathbb{Z}}(a, b)$:

In [70]:
np.random.randint(0, 10, size=3)

array([5, 9, 3])

Sampling elements from a given set, with or without replcement:

In [71]:
np.random.choice(['red', 'green', 'blue'], size=5)

array(['blue', 'green', 'blue', 'red', 'green'], dtype='<U5')

Generating permutations $\sigma \in \mathbb{N}_n$:

In [72]:
np.random.permutation([4, 2, 1])

array([4, 1, 2])

**ℹ️ Tip**: setting the random seed allows for reproducibility of results when randomness is involved. The results are still random, but they are the same ones, every time. Since most scientific libraries delegate their random generation to numpy, `np.random.seed(123)` is sufficient for all. Read more about [random number generation](https://en.wikipedia.org/wiki/Pseudorandom_number_generator).

**💪 Exercise**: generate an array of 6 rows, 3 columns of random integers between `0` and `9`:

In [73]:
np.random.randint(0, 9, size=(6, 3))

array([[7, 4, 6],
       [2, 8, 1],
       [1, 6, 4],
       [3, 1, 4],
       [1, 2, 6],
       [5, 4, 3]])

### Array Accessing

Index, and slice accessing is similar to `list`s:

In [74]:
squares  # to remember what it contains

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [75]:
squares[2]  # remember, zero-indexed

4

In [76]:
squares[2:6]  # slices

array([ 4,  9, 16, 25])

---

It extends naturally to multi-dimensional arrays:

In [77]:
m  # to remember what it contains

array([[5, 2, 3],
       [4, 5, 1],
       [7, 1, 2],
       [6, 2, 9]])

In [78]:
m[:2]  # first two rows

array([[5, 2, 3],
       [4, 5, 1]])

In [79]:
m[:, :2]  # all rows, first two columns

array([[5, 2],
       [4, 5],
       [7, 1],
       [6, 2]])

In [80]:
m[:2, :2]  # first two rows of the first two columns

array([[5, 2],
       [4, 5]])

---

_Fancy_ indexing (this is the actual term) allows for accessing multiple elements at once:

In [81]:
indices = [4, 2, 2]  # can also repeat
squares[indices]

array([16,  4,  4])

In [82]:
row_indices = [0, 1]
col_indices = [0, 2]
m[row_indices, col_indices]

array([5, 1])

**💪 Exercise**: access all rows, columns 2 through 3 of `m`:

In [83]:
m[:, 1:3]

array([[2, 3],
       [5, 1],
       [1, 2],
       [2, 9]])

### Array Iteration

Iteration works the same:

In [84]:
for sq in squares:
    print(sq)

0
1
4
9
16
25
36
49


Enumeration has its n-dimensional counterpart:

In [85]:
for index, element in np.ndenumerate(m):
    print('index', index, 'element', element)

index (0, 0) element 5
index (0, 1) element 2
index (0, 2) element 3
index (1, 0) element 4
index (1, 1) element 5
index (1, 2) element 1
index (2, 0) element 7
index (2, 1) element 1
index (2, 2) element 2
index (3, 0) element 6
index (3, 1) element 2
index (3, 2) element 9


### Array Operations

Arithmetic operations are _vectorized_ — extended for array operations:

In [86]:
squares  # to remember what it contains

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [87]:
squares + 100  # add 100 to each element

array([100, 101, 104, 109, 116, 125, 136, 149])

In [88]:
squares ** .5  # raise every element to the power 0.5 (square root it)

array([0., 1., 2., 3., 4., 5., 6., 7.])

**ℹ️ Tip**: an array containing all `5`s is generated by `np.ones(dim) * 5`

---

Conditional operators as well, and their result is boolean:

In [89]:
squares > 5

array([False, False, False,  True,  True,  True,  True,  True])

In [90]:
squares == 1

array([False,  True, False, False, False, False, False, False])

In [91]:
odd = (squares % 2 == 0)
odd

array([ True, False,  True, False,  True, False,  True, False])

---

There are also unary operators, such as negation:

In [92]:
~odd

array([False,  True, False,  True, False,  True, False,  True])

In [93]:
-squares

array([  0,  -1,  -4,  -9, -16, -25, -36, -49])

---

Aggregations and other more complex operations are available as methods:

In [95]:
squares.sum()  # sum of all elements

140

In [96]:
sum(squares)  # equivalent

140

In [99]:
np.log(squares + 1)

array([0.        , 0.69314718, 1.60943791, 2.30258509, 2.83321334,
       3.25809654, 3.61091791, 3.91202301])

In [100]:
squares.mean()  # equivalent to sum/len

17.5

In [101]:
squares.std()  # standard deviation

16.680827317612277

In [102]:
squares.cumsum()  # cumulative sum

array([  0,   1,   5,  14,  30,  55,  91, 140])

---

In [103]:
a = np.array([2, 0, 4])

In [105]:
a.min()

0

In [104]:
a.argmin()  # the index of the minimum element

1

In [106]:
a.argsort()  # the indices that would sort the array

array([1, 0, 2])

In [107]:
a[a.argsort()]

array([0, 2, 4])

---

Operators naturally extend to multiple dimensions as well:

In [109]:
m

array([[5, 2, 3],
       [4, 5, 1],
       [7, 1, 2],
       [6, 2, 9]])

In [108]:
m * 10

array([[50, 20, 30],
       [40, 50, 10],
       [70, 10, 20],
       [60, 20, 90]])

In [110]:
m == 5

array([[ True, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

Element-wise application of operators between to arrays:

In [111]:
a

array([2, 0, 4])

In [112]:
b = np.array([9, 6, 6])

In [113]:
a + b

array([11,  6, 10])

In [114]:
a * b

array([18,  0, 24])

---

Binary operations:

In [115]:
a = squares > 5
a

array([False, False, False,  True,  True,  True,  True,  True])

In [116]:
b = (squares % 2 == 0)
b

array([ True, False,  True, False,  True, False,  True, False])

In [117]:
a & b

array([False, False, False, False,  True, False,  True, False])

In [118]:
a | b

array([ True, False,  True,  True,  True,  True,  True,  True])

---

In [119]:
x = np.linspace(0, np.pi, num=5)
x

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [120]:
np.sin(x).round(3)

array([0.   , 0.707, 1.   , 0.707, 0.   ])

---

Functions, when applied to multi-dimensional arrays, allow you to specify an axis. In a 2D matrix, that means either column-wise or row-wise:

In [121]:
m  # refresher

array([[5, 2, 3],
       [4, 5, 1],
       [7, 1, 2],
       [6, 2, 9]])

In [122]:
m.sum()  # overall sum of all elements, no axis specified

47

In [123]:
m.sum(axis=0)  # first axis, column wise — one result for each column

array([22, 10, 15])

In [124]:
m.sum(axis=1)  # per each row

array([10, 10, 10, 17])

---

The `*` operator gives the hadamard product (element-wise multiplication) between matrices:

In [ ]:
m * m

Matrix multiplication is done using the `@` operator (previously, using `a.dot(b)`):

In [ ]:
m @ m.transpose()

---

**💪 Exercise**: re-generate the `squares` array, but using numpy:

In [126]:
np.arange(8) ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49])

#### Reshaping

Arrays can be morph into a different (compatible) shape:

In [127]:
squares  # original

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [128]:
squares.reshape(2, 4)  # 2 rows, 4 columns

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]])

In [129]:
squares.reshape(4, 2)  # 4 rows, 2 columns

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49]])

Flatten an array of any shape with `.reshape(-1)`:

In [130]:
m

array([[5, 2, 3],
       [4, 5, 1],
       [7, 1, 2],
       [6, 2, 9]])

In [131]:
m.reshape(-1)

array([5, 2, 3, 4, 5, 1, 7, 1, 2, 6, 2, 9])

In [132]:
image.reshape(-1).shape

(72,)

In [134]:
6 * 4 * 3

72

Transposition (axis inversion):

In [135]:
m.T

array([[5, 4, 7, 6],
       [2, 5, 1, 2],
       [3, 1, 2, 9]])

---

Generating new axes can be useful when certain functions require the data in a particular shape, even if it is degenerated:

In [136]:
squares[:, np.newaxis]  # make each element be a list

array([[ 0],
       [ 1],
       [ 4],
       [ 9],
       [16],
       [25],
       [36],
       [49]])

In [137]:
squares[np.newaxis, :]  # wrap the array

array([[ 0,  1,  4,  9, 16, 25, 36, 49]])

In [138]:
squares.shape  # original shape

(8,)

In [139]:
squares[:, np.newaxis].shape

(8, 1)

In [140]:
squares[np.newaxis, :].shape

(1, 8)

**ℹ️ Tip**: shapes are simply "views" of the underlying data, which is stored the same way, regardless of assigned shape. Read more about how [data is stored internally](https://docs.scipy.org/doc/numpy-1.13.0/reference/internals.html).

**💪 Exercise**: in how many ways can an array of size 12 be reshaped?

In [143]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**👾 Trivia**: [this is why](https://www.youtube.com/watch?v=U6xJfP7-HCc) a base-12 number system would make arithmetic easier.

### Broadcasting

The same operation, `+`, is used both when adding a constant to each element, and also when performing element-wise addition. This concept is extended to arbitrarily many dimensions. The right-hand-side of the operator is _broadcasted_ until it reaches the left-hand-side's shape.

In [144]:
squares + 10

array([10, 11, 14, 19, 26, 35, 46, 59])

In [145]:
tens = [10] * 8  # eight elements, each equal to 10
squares + tens  # behind the scenes, the rhs is broadcasted to match the lhs' shape

array([10, 11, 14, 19, 26, 35, 46, 59])

It becomes non-arbitrary in higher dimensions:

In [146]:
m  # content refresher

array([[5, 2, 3],
       [4, 5, 1],
       [7, 1, 2],
       [6, 2, 9]])

In [147]:
m + [100, 10, 0]  # add these values to each row
# for each row, the first element 

array([[105,  12,   3],
       [104,  15,   1],
       [107,  11,   2],
       [106,  12,   9]])

In [148]:
m + [[1000], [100], [10], [0]]  # add these values to each column
# 

array([[1005, 1002, 1003],
       [ 104,  105,  101],
       [  17,   11,   12],
       [   6,    2,    9]])

Read more about [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html).

### Array Masking

Boolean indexing — access only those elements where the indexing array is `True`:

In [149]:
mask = (squares > 5)

In [150]:
mask

array([False, False, False,  True,  True,  True,  True,  True])

In [151]:
squares[mask]

array([ 9, 16, 25, 36, 49])

**💪 Exercise**: select only even `squares`:

### Array Extension

Since `+` is reserved for addition, array concatenation is done by function:

In [152]:
np.concatenate([squares, squares])

array([ 0,  1,  4,  9, 16, 25, 36, 49,  0,  1,  4,  9, 16, 25, 36, 49])

In the multi-dimensional case:

In [153]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [154]:
b = np.ones((2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [155]:
np.concatenate([a, b])

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [1., 1.],
       [1., 1.]])

---

In [156]:
c = np.zeros((2, 2))

In [157]:
np.vstack([b, c])  # on top of eachother

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [158]:
np.hstack([b, c])  # next to eachother

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

## Pandas Dataframes

Dataframes are easy-to-use, functionality-packed data structures for data handling and analysis. They can be thought of as non-homogenous matrices  for row/column labeled data, which also offer a lot of extra functionality.

In [160]:
import pandas as pd  # the usual abbreviation

### Creation

Instantiate from a 2D array:

In [161]:
pd.DataFrame(m)

0  1  2
0  5  2  3
1  4  5  1
2  7  1  2
3  6  2  9

When working with labeled data, provide a dict of `column_name : value_for_each_row`:

In [233]:
students = pd.DataFrame({
    'height':    np.random.randint(150, 200, size=5),
    'weight':    np.random.randint(50,  100, size=5),
    'graduated': np.random.random(size=5) > .5,  # same as np.random.randint(0, 1, size=10).astype(bool)
})

Each row is an observation (i.e.: a student), each column is a variable (i.e.: a measurement):

In [234]:
students

height  weight  graduated
0     168      57       True
1     187      62       True
2     159      86      False
3     186      89       True
4     152      97      False

_Note_: since randomness is involved, when you run this notebook, you'll likely see different results.

Dataframes are implicitly indexed by integers, but rows can be assigned more descriptive indices:

In [235]:
students.index = list('abcde')

In [236]:
students

height  weight  graduated
a     168      57       True
b     187      62       True
c     159      86      False
d     186      89       True
e     152      97      False

**💪 Exercise**: create a new dataframe, `food_stats`, which contains ratings, on a 1-3 scale for `tasty`, `healthy` and whether you had it recently (`had_recently`) for the following types of food: `pizza`, `carrot`, `chocolate`, `banana`:

In [237]:
food_stats = pd.DataFrame({
    'tasty':        [2, 1, 3, 2],
    'healthy':      [1, 3, 2, 3],
    'had_recently': [True, True, False, True],
}, index=['pizza', 'carrot', 'chocolate', 'banana'])

food_stats

tasty  healthy  had_recently
pizza          2        1          True
carrot         1        3          True
chocolate      3        2         False
banana         2        3          True

### Properties

Shape and data type are extended to dataframes as well:

In [238]:
len(students)  # size of first dimension, i.e.: number of rows

5

In [239]:
students.shape

(5, 3)

In [240]:
students.dtypes

height       int64
weight       int64
graduated     bool
dtype: object

In [241]:
students.height.astype(float)

a    168.0
b    187.0
c    159.0
d    186.0
e    152.0
Name: height, dtype: float64

**💪 Exercise**: check the `shape` and `dtypes` of your `food_stats`:

In [242]:
food_stats.shape

(4, 3)

In [243]:
food_stats.dtypes

tasty           int64
healthy         int64
had_recently     bool
dtype: object

### Accessing

Access rows elements by index:

In [244]:
students

height  weight  graduated
a     168      57       True
b     187      62       True
c     159      86      False
d     186      89       True
e     152      97      False

In [245]:
students.loc['a']  # the observations for student A

height        168
weight         57
graduated    True
Name: a, dtype: object

Access rows by their position, regardless of index name:

In [246]:
students.iloc[0]

height        168
weight         57
graduated    True
Name: a, dtype: object

Slices are extended row-wise:

In [247]:
students[:3]

height  weight  graduated
a     168      57       True
b     187      62       True
c     159      86      False

In [248]:
students.head(3)

height  weight  graduated
a     168      57       True
b     187      62       True
c     159      86      False

---

Access a specific column:

In [249]:
students['graduated']

a     True
b     True
c    False
d     True
e    False
Name: graduated, dtype: bool

**Tip**: sometimes, reserved keys cannot be used to access certain columns (e.g.: `size`), so you must use the dict-like syntax

In [250]:
students.graduated  # we can also access column-wise

a     True
b     True
c    False
d     True
e    False
Name: graduated, dtype: bool

Access multiple columns at once:

In [251]:
columns = ['weight', 'height']
students[columns]

weight  height
a      57     168
b      62     187
c      86     159
d      89     186
e      97     152

Masking is performed row-wise by providing a boolean array with the same length as the number of rows:

In [252]:
students[students.graduated]

height  weight  graduated
a     168      57       True
b     187      62       True
d     186      89       True

---

Randomly sample rows:

In [253]:
students.sample(3)

height  weight  graduated
a     168      57       True
d     186      89       True
e     152      97      False

In [254]:
students.sample(frac=.5)  # half of all rows

height  weight  graduated
c     159      86      False
b     187      62       True

In [255]:
len(students)

5

---

Iterating over the dataframe defaults to going over its columns:

In [256]:
for column in students:
    print(column)

height
weight
graduated


`iterrows()` is used to iterate over each row:

In [257]:
for student, row in students.iterrows():
    print(student, row.height, row.weight)

a 168 57
b 187 62
c 159 86
d 186 89
e 152 97


**💪 Exercise**: access the `tasty` column, rows 2 through 3 of `food_stats`:

**💪 Exercise**: select rows for students yet to graduate:

In [258]:
students[~students.graduated]

height  weight  graduated
c     159      86      False
e     152      97      False

### Extension

To add a new row, just specify it's index (`loc`) or positional index (`iloc`) and the value for each column:

In [259]:
students.loc['x'] = (170, 70, True)

In [260]:
students

height  weight  graduated
a     168      57       True
b     187      62       True
c     159      86      False
d     186      89       True
e     152      97      False
x     170      70       True

**ℹ️ Tip**: even though `df.iloc[len(df) - 1] = ...` can be used to append at the end of any dataframe, this is not recommended. If you wish to create a dataframe iteratively, instead of appending each element, store them in a different container and convert the data to a dataframe at the end. This is also the reason why there is no `append` function for dataframes.

To add a new column, assign it directly to the dataframe and specify a value for each row:

In [261]:
students['age'] = np.random.randint(18, 24, size=len(students))

In [262]:
students

height  weight  graduated  age
a     168      57       True   22
b     187      62       True   21
c     159      86      False   19
d     186      89       True   19
e     152      97      False   18
x     170      70       True   20

**ℹ️ Tip**: this syntax must be used for column creation. `df.column` only works for accessing existing columns.

Create a column based on another:

In [263]:
students['can_ride'] = (students.height > 170)  # "you must be this tall to ride the roller coaster"

In [264]:
students

height  weight  graduated  age  can_ride
a     168      57       True   22     False
b     187      62       True   21      True
c     159      86      False   19     False
d     186      89       True   19      True
e     152      97      False   18     False
x     170      70       True   20     False

---

Add multiple new rows, from another dataframe:

In [265]:
new_students = pd.DataFrame({
    'height': [160, 180],
    'weight': [ 60,  80],
})

new_students

height  weight
0     160      60
1     180      80

In [266]:
students = pd.concat([students, new_students], sort=False)
students

height  weight graduated   age can_ride
a     168      57      True  22.0    False
b     187      62      True  21.0     True
c     159      86     False  19.0    False
d     186      89      True  19.0     True
e     152      97     False  18.0    False
x     170      70      True  20.0    False
0     160      60       NaN   NaN      NaN
1     180      80       NaN   NaN      NaN

_Note_ it's `pd.concat` but `np.concatenate`

Add multiple new columns, from another dataframe:

In [267]:
n_students = len(students)

new_info = pd.DataFrame({
    'fav_number':   np.random.randint(0, 100, size=n_students),
    'fav_icecream': np.random.choice(['vanilla', 'chocolate', 'strawberry'], size=n_students),
})

In [269]:
new_info.index = students.index  # set the same index, to make merging (and viewing) easier
new_info

fav_number fav_icecream
a          29    chocolate
b          95   strawberry
c          16      vanilla
d          80    chocolate
e          16   strawberry
x          94    chocolate
0          41   strawberry
1          60   strawberry

In [270]:
students = students.merge(new_info, left_index=True, right_index=True)
students

height  weight graduated   age can_ride  fav_number fav_icecream
a     168      57      True  22.0    False          29    chocolate
b     187      62      True  21.0     True          95   strawberry
c     159      86     False  19.0    False          16      vanilla
d     186      89      True  19.0     True          80    chocolate
e     152      97     False  18.0    False          16   strawberry
x     170      70      True  20.0    False          94    chocolate
0     160      60       NaN   NaN      NaN          41   strawberry
1     180      80       NaN   NaN      NaN          60   strawberry

**💪 Exercise**: add a new entry for `hamburger` in the `food_stats` dataframe:

### Missing Values

Since we only provided the `height` and `weight` measurements, for the new students, `nan` (not a number) is placed by default for the other columns:

In [271]:
students

height  weight graduated   age can_ride  fav_number fav_icecream
a     168      57      True  22.0    False          29    chocolate
b     187      62      True  21.0     True          95   strawberry
c     159      86     False  19.0    False          16      vanilla
d     186      89      True  19.0     True          80    chocolate
e     152      97     False  18.0    False          16   strawberry
x     170      70      True  20.0    False          94    chocolate
0     160      60       NaN   NaN      NaN          41   strawberry
1     180      80       NaN   NaN      NaN          60   strawberry

Missing value detection:

In [272]:
pd.isna(students)

height  weight  graduated    age  can_ride  fav_number  fav_icecream
a   False   False      False  False     False       False         False
b   False   False      False  False     False       False         False
c   False   False      False  False     False       False         False
d   False   False      False  False     False       False         False
e   False   False      False  False     False       False         False
x   False   False      False  False     False       False         False
0   False   False       True   True      True       False         False
1   False   False       True   True      True       False         False

Column-wise:

In [273]:
pd.isna(students.age)

a    False
b    False
c    False
d    False
e    False
x    False
0     True
1     True
Name: age, dtype: bool

The easiest method for handling missing data is dropping the observation alltogether:

In [274]:
students.dropna()

height  weight graduated   age can_ride  fav_number fav_icecream
a     168      57      True  22.0    False          29    chocolate
b     187      62      True  21.0     True          95   strawberry
c     159      86     False  19.0    False          16      vanilla
d     186      89      True  19.0     True          80    chocolate
e     152      97     False  18.0    False          16   strawberry
x     170      70      True  20.0    False          94    chocolate

Another method is filling it with some default value:

In [275]:
students.fillna({
    'graduated': False,
    'can_ride':  False,
    'age':       20,
})

height  weight  graduated   age  can_ride  fav_number fav_icecream
a     168      57       True  22.0     False          29    chocolate
b     187      62       True  21.0      True          95   strawberry
c     159      86      False  19.0     False          16      vanilla
d     186      89       True  19.0      True          80    chocolate
e     152      97      False  18.0     False          16   strawberry
x     170      70       True  20.0     False          94    chocolate
0     160      60      False  20.0     False          41   strawberry
1     180      80      False  20.0     False          60   strawberry

More methods for handling missing value will be explored in workshop 4.

**ℹ️ Tip**: the reason why we must use `pd.isna` to identify NANs, instead of `== np.nan` is because `np.nan` is a special element, which, by design, is not equal to anything, not even `np.nan`. Read more about [ternary logic](https://en.wikipedia.org/wiki/Three-valued_logic) and non-[finite numpy numbers](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.isfinite.html#numpy.isfinite).

### Deleting

Delete some columns:

In [276]:
students.drop(['weight', 'age'], axis=1)

height graduated can_ride  fav_number fav_icecream
a     168      True    False          29    chocolate
b     187      True     True          95   strawberry
c     159     False    False          16      vanilla
d     186      True     True          80    chocolate
e     152     False    False          16   strawberry
x     170      True    False          94    chocolate
0     160       NaN      NaN          41   strawberry
1     180       NaN      NaN          60   strawberry

Delete some rows, index-wise:

In [277]:
students.drop(['a', 'x'], axis=0)

height  weight graduated   age can_ride  fav_number fav_icecream
b     187      62      True  21.0     True          95   strawberry
c     159      86     False  19.0    False          16      vanilla
d     186      89      True  19.0     True          80    chocolate
e     152      97     False  18.0    False          16   strawberry
0     160      60       NaN   NaN      NaN          41   strawberry
1     180      80       NaN   NaN      NaN          60   strawberry

---

Deleting rows based on a boolean filtering is done by masking:

In [278]:
mask = (students.age > 21)  # filter underage ones
students[mask]

height  weight graduated   age can_ride  fav_number fav_icecream
a     168      57      True  22.0    False          29    chocolate

Dropping duplicate rows can be done using `drop_duplicate`, but since our dataframe contains no such rows, we will restrict it to duplicates on just the `can_ride` and `fav_icecream` columns:

In [279]:
students

height  weight graduated   age can_ride  fav_number fav_icecream
a     168      57      True  22.0    False          29    chocolate
b     187      62      True  21.0     True          95   strawberry
c     159      86     False  19.0    False          16      vanilla
d     186      89      True  19.0     True          80    chocolate
e     152      97     False  18.0    False          16   strawberry
x     170      70      True  20.0    False          94    chocolate
0     160      60       NaN   NaN      NaN          41   strawberry
1     180      80       NaN   NaN      NaN          60   strawberry

In [280]:
students.drop_duplicates(subset=['can_ride', 'fav_icecream'], keep='first')

height  weight graduated   age can_ride  fav_number fav_icecream
a     168      57      True  22.0    False          29    chocolate
b     187      62      True  21.0     True          95   strawberry
c     159      86     False  19.0    False          16      vanilla
d     186      89      True  19.0     True          80    chocolate
e     152      97     False  18.0    False          16   strawberry
0     160      60       NaN   NaN      NaN          41   strawberry

---

Deleting, much like any operation in the next subsection, does not operate _in place_. This means the `drop` function returns a new dataframe object, which is created by (deep) copying the original one and applying the operation on it. Writing your own functions in such a way helps with preventing unexpected and hard to trace side effects. It also allows for method chaining `df.transpose().mean().round()`. Read more about [functional programming](https://hackernoon.com/learn-functional-python-in-10-minutes-to-2d1651dece6f) and [immutability in Python](https://www.pythonforthelab.com/blog/mutable-and-immutable-objects/).

If you do wish to "update" the same object, assign the result to the same variable:

In [300]:
students = students.dropna()

Some functions also offer the `inplace` option:

In [ ]:
students.dropna(inplace=True)  # equivalent to above

**💪 Exercise**: Drop the `graduated` column from `students` (not in place!):

### Dataframe Operations

Array-wise functions and operations are naturally extended to dataframes

**ℹ️ Tip**: a dataframe is composed by multiple `pd.Series`. Each column can be a series, and each row can be a series. A series is a "labeled list" — where each `value` has an `index`.

In [213]:
students  # contents refresher

height  weight graduated   age can_ride  fav_number fav_icecream
a     181      53      True  19.0     True          77    chocolate
b     195      79     False  19.0     True          68      vanilla
c     192      52     False  18.0     True          87      vanilla
d     175      68      True  21.0     True          49      vanilla
e     172      63     False  23.0     True          54    chocolate
x     170      70      True  20.0    False          41    chocolate
0     160      60       NaN   NaN      NaN          60    chocolate
1     180      80       NaN   NaN      NaN          40    chocolate

#### Arithmetic

In [214]:
students.weight - 10  # if only losing weight was this easy 😅

a    43
b    69
c    42
d    58
e    53
x    60
0    50
1    70
Name: weight, dtype: int64

In [215]:
students.height + students.weight  # note that the resulting series still has the same indices

a    234
b    274
c    244
d    243
e    235
x    240
0    220
1    260
dtype: int64

In [216]:
students.sum()

height                                                       1425
weight                                                        525
graduated                                                       3
age                                                           120
can_ride                                                        5
fav_number                                                    476
fav_icecream    chocolatevanillavanillavanillachocolatechocola...
dtype: object

In [217]:
students.mean()

height        178.125000
weight         65.625000
graduated       0.500000
age            20.000000
can_ride        0.833333
fav_number     59.500000
dtype: float64

**ℹ️ Tip**: The sum of the boolean series `graduated` is the number of people that graduated. The mean of `graduated` is the sum divided by the total number of students, which is precisely the percentage of students that graduated.

Most operations accept an `axis` argument, which can either be `0` (column-wise, default), or `1` (row-wise):

In [218]:
students.mean(axis=1)  # the average for each student, of their height, weight and graduation status.. which doesn't make much sense

a     82.500000
b     90.250000
c     87.250000
d     78.250000
e     78.000000
x     75.250000
0     93.333333
1    100.000000
dtype: float64

**💪 Exercise**: get the sums of the `tasty` and `healthy` ratings in `food_stats`:

#### Logical

In [223]:
students.age > 21

a    False
b    False
c    False
d    False
e     True
x    False
Name: age, dtype: bool

In [224]:
students.graduated & ~students.can_ride  # students who graduated but cannot ride

a     True
b    False
c    False
d     True
e    False
x     True
dtype: bool

In [225]:
students.graduated.any()

True

In [226]:
students.graduated.all()

False

In [227]:
students == 21

height  weight  graduated    age  can_ride  fav_number  fav_icecream
a   False   False      False  False     False       False         False
b   False   False      False  False     False       False         False
c   False   False      False  False     False       False         False
d   False   False      False   True     False       False         False
e   False   False      False  False     False       False         False
x   False   False      False  False     False       False         False

**💪 Exercise**: which tasty ($\ge 2$) food items have you had recently?

#### String Functions

The raw string values of textual variables can be accessed with `.str`:

In [281]:
students.fav_icecream

a     chocolate
b    strawberry
c       vanilla
d     chocolate
e    strawberry
x     chocolate
0    strawberry
1    strawberry
Name: fav_icecream, dtype: object

In [282]:
students.fav_icecream.str.title()

a     Chocolate
b    Strawberry
c       Vanilla
d     Chocolate
e    Strawberry
x     Chocolate
0    Strawberry
1    Strawberry
Name: fav_icecream, dtype: object

In [283]:
students.fav_icecream.str.replace('straw', 'banned-')

a       chocolate
b    banned-berry
c         vanilla
d       chocolate
e    banned-berry
x       chocolate
0    banned-berry
1    banned-berry
Name: fav_icecream, dtype: object

In [284]:
students.fav_icecream.str.contains('e')

a     True
b     True
c    False
d     True
e     True
x     True
0     True
1     True
Name: fav_icecream, dtype: bool

**💪 Exercise**: make the name (the `index`) of the food items in `food_stats` uppercase:

#### Arbitrary Functions

In [285]:
students.height.apply(lambda w: (w // 10) * 10)  # apply to each element of a column

a    160
b    180
c    150
d    180
e    150
x    170
0    160
1    180
Name: height, dtype: int64

In [286]:
students.apply(lambda row: row.height + row.weight, axis=1)  # apply row-wise

a    225
b    249
c    245
d    275
e    249
x    240
0    220
1    260
dtype: int64

In [287]:
def relabel_boolean(x):
    # if the argument is not a boolean, leave it as it is
    if type(x) is not bool:
        return x
    return 'yes' if x is True else 'no'

In [288]:
students.applymap(relabel_boolean)  # apply element-wise

height  weight graduated   age can_ride  fav_number fav_icecream
a     168      57       yes  22.0       no          29    chocolate
b     187      62       yes  21.0      yes          95   strawberry
c     159      86        no  19.0       no          16      vanilla
d     186      89       yes  19.0      yes          80    chocolate
e     152      97        no  18.0       no          16   strawberry
x     170      70       yes  20.0       no          94    chocolate
0     160      60       NaN   NaN      NaN          41   strawberry
1     180      80       NaN   NaN      NaN          60   strawberry

#### Statistical

One of the most useful shortcuts is `describe`, which quickly provides a list of descriptive statistics about each numeric column:

In [289]:
students.describe().round(2)

height  weight    age  fav_number
count    8.00    8.00   6.00        8.00
mean   170.25   75.12  19.83       53.88
std     13.06   14.97   1.47       33.11
min    152.00   57.00  18.00       16.00
25%    159.75   61.50  19.00       25.75
50%    169.00   75.00  19.50       50.50
75%    181.50   86.75  20.75       83.50
max    187.00   97.00  22.00       95.00

90% of the values are lower than the 90th percentile. This can be used for outlier detection, which will be explored in workshop 4.

In [290]:
students.describe(percentiles=[.1, .5, .9, .95]).round(3)

height  weight     age  fav_number
count    8.000   8.000   6.000       8.000
mean   170.250  75.125  19.833      53.875
std     13.058  14.971   1.472      33.112
min    152.000  57.000  18.000      16.000
10%    156.900  59.100  18.500      16.000
50%    169.000  75.000  19.500      50.500
90%    186.300  91.400  21.500      94.300
95%    186.650  94.200  21.750      94.650
max    187.000  97.000  22.000      95.000

---

Categorical variables aggregations:

In [291]:
students.fav_icecream.value_counts()

strawberry    4
chocolate     3
vanilla       1
Name: fav_icecream, dtype: int64

In [292]:
students.fav_icecream.unique()

array(['chocolate', 'strawberry', 'vanilla'], dtype=object)

In [293]:
students.fav_icecream.nunique()  # when you need just the amount of unique items, not their actual values

3

---

Two variables have high _pair-wise correlation_ (Pearson) when one is dependent on the other: there is a linear relationship between the two:

In [294]:
students.corr()

height    weight       age  fav_number
height      1.000000 -0.203343  0.427368    0.811239
weight     -0.203343  1.000000 -0.979318   -0.273163
age         0.427368 -0.979318  1.000000    0.281335
fav_number  0.811239 -0.273163  0.281335    1.000000

Two variables have high _covariance_ when they then to show similar behavior: greater values in one correspond to greater values in the other:

In [295]:
students.cov()

height      weight        age   fav_number
height      170.500000  -39.750000   8.866667   350.750000
weight      -39.750000  224.125000 -23.233333  -135.410714
age           8.866667  -23.233333   2.166667    16.000000
fav_number  350.750000 -135.410714  16.000000  1096.410714

Positive _skewness_ indicates left-leaning distributions:

In [296]:
students.age.skew()

0.41807152029954664

Positive _kurtosis_ indicates that the distribution has heavy tails and sharp peaks:

In [297]:
students.age.kurt()

-0.859171597633134

Read more about [distribution measures](https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/basic-statistics/inference/supporting-topics/data-concepts/how-skewness-and-kurtosis-affect-your-distribution/).

**💪 Exercise**: `describe` your `food_stats`:

#### Ordering

Sort by the index:

In [299]:
students

height  weight graduated   age can_ride  fav_number fav_icecream
a     168      57      True  22.0    False          29    chocolate
b     187      62      True  21.0     True          95   strawberry
c     159      86     False  19.0    False          16      vanilla
d     186      89      True  19.0     True          80    chocolate
e     152      97     False  18.0    False          16   strawberry
x     170      70      True  20.0    False          94    chocolate
0     160      60       NaN   NaN      NaN          41   strawberry
1     180      80       NaN   NaN      NaN          60   strawberry

In [301]:
students.sort_index()

height  weight graduated   age can_ride  fav_number fav_icecream
a     168      57      True  22.0    False          29    chocolate
b     187      62      True  21.0     True          95   strawberry
c     159      86     False  19.0    False          16      vanilla
d     186      89      True  19.0     True          80    chocolate
e     152      97     False  18.0    False          16   strawberry
x     170      70      True  20.0    False          94    chocolate

Sort by (a combination of) column(s):

In [302]:
students.sort_values(by=['fav_number', 'age'], ascending=True)

height  weight graduated   age can_ride  fav_number fav_icecream
e     152      97     False  18.0    False          16   strawberry
c     159      86     False  19.0    False          16      vanilla
a     168      57      True  22.0    False          29    chocolate
d     186      89      True  19.0     True          80    chocolate
x     170      70      True  20.0    False          94    chocolate
b     187      62      True  21.0     True          95   strawberry

Compute each row's rank (average ranks in case of equality):

In [303]:
students.fav_number.rank()

a    3.0
b    6.0
c    1.5
d    4.0
e    1.5
x    5.0
Name: fav_number, dtype: float64

**💪 Exercise**: sort your `food_stats` by `tasty`est first:

### Data Transformations

Restructuring operations. Same data, but different view, more fitted for the downstream task.

Transpose rows and columns (keeping labels):

In [304]:
students.T

a           b        c          d           e          x
height              168         187      159        186         152        170
weight               57          62       86         89          97         70
graduated          True        True    False       True       False       True
age                  22          21       19         19          18         20
can_ride          False        True    False       True       False      False
fav_number           29          95       16         80          16         94
fav_icecream  chocolate  strawberry  vanilla  chocolate  strawberry  chocolate

Transform a categorical variable into dummy variables:

In [305]:
pd.get_dummies(students.fav_icecream)

chocolate  strawberry  vanilla
a          1           0        0
b          0           1        0
c          0           0        1
d          1           0        0
e          0           1        0
x          1           0        0

### Group By

_Grouping_ puts together rows according to the values for a certain variable:

In [306]:
# exemplify on a new dataframe
performance = pd.DataFrame([
    ('Alice', 'CS 101', 4.0),
    ('Alice', 'CS 102', 3.0),
    ('Alice', 'EE 201', 4.0),
    ('Bob',   'CS 101', 3.0),
    ('Bob',   'EE 201', 4.0),
], columns=['student', 'class', 'grade'])

In [307]:
performance

student   class  grade
0   Alice  CS 101    4.0
1   Alice  CS 102    3.0
2   Alice  EE 201    4.0
3     Bob  CS 101    3.0
4     Bob  EE 201    4.0

In order to see the effects of grouping, we apply an aggregation on all the rows for each student:

In [308]:
performance.groupby('student').grade.mean()

student
Alice    3.666667
Bob      3.500000
Name: grade, dtype: float64

---

Group by multiple variables:

In [309]:
students.groupby(['graduated', 'fav_icecream']).age.mean()

graduated  fav_icecream
False      strawberry      18.000000
           vanilla         19.000000
True       chocolate       20.333333
           strawberry      21.000000
Name: age, dtype: float64

---

Iterate over the `groupby` object, feature value (student name here) and the rows for that value:

In [310]:
for student, classes in performance.groupby('student'):
    print(student, 'took', len(classes), 'classes, with an average of', classes.grade.mean().round(2))

Alice took 3 classes, with an average of 3.67
Bob took 2 classes, with an average of 3.5


**💪 Exercise**: get the maximum grade of each student `performance`:

### Pivot

_Pivoting_ "flips" the data according and applies an function. Select a discrete variable for the columns, one for the rows, and you get the unique values for each. Each observations in the original dataframe, falls into one such value intersection. Pick an aggregation to apply to that set of observations.

For example, if want to know the average `height` and `weight` for those students that `graduated` and those that did not:

In [311]:
pd.pivot_table(
    students,
    index='graduated',
    values=['height', 'weight'],
    aggfunc='mean',
)

height  weight
graduated                
False      155.50    91.5
True       177.75    69.5

Or the maximum `height` and `weight` instead:

In [312]:
pd.pivot_table(
    students,
    index='graduated',
    values=['height', 'weight'],
    aggfunc='max',
)

height  weight
graduated                
False         159      97
True          187      89

---

A special case of pivoting is _cross tabulation_, which returns the counts at each feature value intersection:

In [ ]:
pd.crosstab(students.fav_icecream, students.graduated, margins=True)

**💪 Exercise**: get `mean` of `age` and `height` for students who `can_ride` and those who can't:

### Melt

_Melting_ can be thought of as the reverse of pivoting.

In [313]:
# exemplify on a new dataframe
height_evolution = pd.DataFrame({
    'Alice': np.linspace(160, 190, num=5),
    'Bob':   np.linspace(170, 180, num=5),
    'year':  range(2000, 2005),
})

In [314]:
height_evolution

Alice    Bob  year
0  160.0  170.0  2000
1  167.5  172.5  2001
2  175.0  175.0  2002
3  182.5  177.5  2003
4  190.0  180.0  2004

Currently, each student has their own column. But that is the same type of information. So, we can melt them into a single `student` column:

In [315]:
melted = height_evolution.melt(
    id_vars='year',
    value_vars=['Alice', 'Bob'],

    var_name='student',
    value_name='height',
)
melted

year student  height
0  2000   Alice   160.0
1  2001   Alice   167.5
2  2002   Alice   175.0
3  2003   Alice   182.5
4  2004   Alice   190.0
5  2000     Bob   170.0
6  2001     Bob   172.5
7  2002     Bob   175.0
8  2003     Bob   177.5
9  2004     Bob   180.0

### Join

_Joining_ combines two tables, based on a common variable

In [316]:
height_stats = height_evolution.describe().T[['min', 'max']].rename(columns=lambda c: c + '_height')
height_stats

min_height  max_height
Alice       160.0       190.0
Bob         170.0       180.0
year       2000.0      2004.0

_Note_: since these are column-wise statistics, we also get the smallest and largest values for `year`.

Both tables have the `student` column, which is the one we join on. For every row where `student` is `"Alice"`, combine the information from the `performance` dataframe (`class` and `grade`) with the information from the the other dataframe (`min_height` and `max_height`).

In [317]:
performance.join(height_stats, on='student')

student   class  grade  min_height  max_height
0   Alice  CS 101    4.0       160.0       190.0
1   Alice  CS 102    3.0       160.0       190.0
2   Alice  EE 201    4.0       160.0       190.0
3     Bob  CS 101    3.0       170.0       180.0
4     Bob  EE 201    4.0       170.0       180.0

_Note_: since `year` is not among `performance.student` values, the default left join ignores that entry. Learn more about [join types](http://www.sql-join.com/sql-join-types/).

### Time Series

In [ ]:
from datetime import datetime

In [ ]:
# number of pages read for the first week of classes
pages_read = pd.DataFrame({
    'Alice': np.random.randint(0, 50, size=7),
    'Bob':   np.random.randint(0, 20, size=7),
    'date': pd.date_range('7 Jan 2019', periods=7)
})

pages_read

Comparison operations can be done against a `datetime`-compatible object:

In [ ]:
late_start = datetime(year=2019, month=1, day=10)  # it's not fair to start counting that early

In [ ]:
pages_read[pages_read.date > late_start]

While dates represent specific timepoints (of various granularity), the difference between two such objects is a _time delta_: a duration, not a date:

In [ ]:
late_start - pages_read.date.iloc[0]

It can be instantiated by parsing natural language:

In [ ]:
pd.Timedelta('7 days 5 hours 3 minutes')

Timedeltas can be used to offset date objects:

In [ ]:
pages_read.date + pd.Timedelta(7, 'd')  # much better, a whole week later

### Hierarchical Indices

In [ ]:
enrollment = pd.DataFrame({
    'level':    np.random.choice(['grad', 'undergrad', 'phd'], size=20),
    'school':   np.random.choice(['Viterbi', 'Price', 'Marshall', 'Dornsife'], size=20),
    'students': np.random.randint(200, 5_000, size=20),
    'faculty':  np.random.randint(50,  500,   size=20),
}).drop_duplicates(subset=['level', 'school'])

enrollment

In [ ]:
enrollment.set_index(['school', 'level']).sort_index()

---

In [ ]:
locations = pd.DataFrame({
    'Alice': ('San Francisco', 'CA', 'Los Angeles', 'CA'),
    'Bob':   ('Rochester', 'NY', 'Los Angeles', 'CA'),
    'Chris': ('Las Vegas', 'NV', 'Pennsylvania', 'PA'),
}).T

locations.columns = pd.MultiIndex.from_product([
    ['home', 'school'],
    ['city', 'state']
], names=['purpose', 'address'])

locations

Read more about [advanced indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html)

### Loading and Saving Dataframes

Data will almost always be loaded from an external source.

Load from JSON (open the file in the file browser to check out the source):

In [ ]:
pd.read_json('example_files/objects.json')

Load from CSV (again, the file is in the `example_files` folder):

In [ ]:
pd.read_csv('example_files/tabular.csv')

**ℹ️ Tip**: the CSV format is extremely common. There is a huge number of options available for loading such files. Read more about them [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

Load directly from an URL, letting Pandas do the downloading (paste that link into your browser to check the source):

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/stefan-niculae/viz-workshop/master/example_files/tabular.csv')

Load directly from an archive, letting Pandas do the uncompressing (find the file and extract it in your local file browser to check the source):

In [ ]:
pd.read_csv('example_files/archived.csv.zip')

---

Saving data (check the result after running in the file browser):

In [ ]:
performance.to_csv('students_performance.csv')

**ℹ️ Tip**: if the index is meaningless (e.g.: just the default sequential one), avoid wasting space and slightly encumbering the reading process by omitting it with `ignore_index=True`.

## Further Reading
 - Numpy: 
   - [cheatsheet](https://www.dataquest.io/blog/large_files/numpy-cheat-sheet.pdf)
   - [official quickstart guide](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html)
   - [official reference](https://docs.scipy.org/doc/numpy/reference/index.html#reference)
 - Scipy: [tutorial](https://docs.scipy.org/doc/scipy/reference/tutorial/index.html)
 - Pandas:
   - [visual cheatsheet](http://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)
   - [cookbook](https://chrisalbon.com/#python)
   - [gotchas](https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html#gotchas)
 - Python/Numpy/Scipy/Matplotlib: [quick tutorial](http://cs231n.github.io/python-numpy-tutorial/)
 
Links to more details about particular concepts are placed at the end of their respective (sub)sections.